assets:
  compress:
      css: true
      js: true
  features:
    automatic_img_size: true
  sources:
    - _assets/fonts
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - _vendor/
  assets:
    - _assets/colour.jpg

baseurl: /afridakari/

exclude:
  - .bowerrc
  - .travis.yml
  - bin/*
  - bower.json
  - circle.yml
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor

ga_analytics: # Add Google Analytics tracking code

gems:
  - jekyll-assets
  - jekyll-sitemap

name: Afridakari
description: > # We at Afridakari had the vision to create a range of products
 that is made from the finest natural ingredients, which is scientifically
 proven to work and will bring you happiness by giving the life back to your hair.

permalink: pretty

url: https://www.afridakari.co.za
